apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod-2
spec:
  containers:
  - name: busybox-container
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ['echo "hello world"; exit 0']
  restartPolicy: Never
