apiVersion: batch/v1
kind: Job
metadata:
  name: busybox-job
spec:
  template:
    spec:
      containers:
      - name: busybox-container
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["echo 'hello world'; exit 0"]
      restartPolicy: Never
  backoffLimit: 0
