apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: consumer
  name: consumer
  namespace: secret-ops
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret
  containers:
    - name: nginx-container
      volumeMounts:
      - name: secret-volume
        mountPath: /var/app
        readOnly: true
  containers:
  - command:
    - sleep
    - infinity
    image: nginx
    name: consumer
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
