apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: consumer
  name: consumer
  namespace: secret-ops
spec:
  containers:
    - name: nginx-container
      envFrom:
      - secretRef:
          name: ext-service-secret
  containers:
  - command:
    - sleep
    - infinity
    image: nginx
    name: consumer
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
