apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"run":"consumer"},"name":"consumer","namespace":"secret-ops"},"spec":{"containers":[{"command":["sleep","infinity"],"image":"nginx","name":"consumer","resources":{}}],"dnsPolicy":"ClusterFirst","restartPolicy":"Never"},"status":{}}
  creationTimestamp: "2024-01-17T12:55:24Z"
  labels:
    run: consumer
  name: consumer
  namespace: secret-ops
  resourceVersion: "39703"
  uid: ac85bb47-6a56-4508-9945-d69f892fe07b
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: nginx
    imagePullPolicy: Always
    name: consumer
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-4h95l
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-4h95l
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-17T12:55:24Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-17T12:55:28Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-17T12:55:28Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-17T12:55:24Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://715d0beb3160c11e57ef10148897fe2f2b1aa3cdde49279d24aca285c7511b85
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:4c0fdaa8b6341bfdeca5f18f7837462c80cff90527ee35ef185571e1c327beac
    lastState: {}
    name: consumer
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-01-17T12:55:27Z"
  hostIP: 192.168.49.2
  phase: Running
  podIP: 10.244.1.56
  podIPs:
  - ip: 10.244.1.56
  qosClass: BestEffort
  startTime: "2024-01-17T12:55:24Z"
