apiVersion: v1
kind: Namespace
metadata:
  name: limitrange

---

apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limitrange
  namespace: limitrange
spec:
  limits:
  - type: Container
    default:
      memory: 200Mi
    defaultRequest:
      memory: 100Mi
    max:
      memory: 500Mi
    min:
      memory: 100Mi
