apiVersion: v1
kind: Pod
metadata:
  name: nginx-busybox-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-volume
      mountPath: /usr/share/nginx/html
  - name: busybox-container
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
    - "wget -O /work-dir/index.html http://neverssl.com/online; sleep 3600"
    volumeMounts:
    - name: shared-volume
      mountPath: /work-dir
  volumes:
  - name: shared-volume
    emptyDir: {}
