apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-limitrange
  namespace: limitrange
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    resources:
      requests:
        memory: "150Mi"
