apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-pod-username
  name: nginx-pod-username
spec:
  containers:
    - name: nginx-container
      env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret2
            key: username
  containers:
  - image: nginx
    name: nginx-pod-username
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
