apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-pod-secret
  name: nginx-pod-secret
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: mysecret2
  containers:
    - name: nginx-container
      volumeMounts:
      - name: secret-volume
        mountPath: /etc/foo
  containers:
  - command:
    - sleep
    - infinity
    image: nginx
    name: nginx-pod-secret
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
